# Generated by Django 3.0.7 on 2020-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('section_name', models.CharField(max_length=200)),
                ('section_url', models.CharField(max_length=1024)),
                ('section_desc', models.CharField(max_length=1024)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
