# Generated by Django 3.0.7 on 2020-06-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category_name', models.CharField(max_length=100)),
                ('category_url', models.CharField(max_length=100)),
                ('category_desc', models.CharField(max_length=1024)),
                ('meta_tags', models.CharField(default='', max_length=1024)),
                ('meta_keywords', models.CharField(default='', max_length=2048)),
                ('meta_description', models.CharField(default='', max_length=5000)),
                ('category_image', models.ImageField(default='', upload_to='media/BackendImages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
