# Generated by Django 3.0.7 on 2020-06-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='section_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
