# Generated by Django 3.0.7 on 2020-06-15 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0003_auto_20200615_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='section_name',
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelsapp.Section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to='BackendImages'),
        ),
    ]
