# Generated by Django 3.0.7 on 2020-06-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0004_auto_20200615_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
