# Generated by Django 3.0.7 on 2020-06-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0009_remove_category_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelsapp.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelsapp.Section'),
            preserve_default=False,
        ),
    ]
