# Generated by Django 3.0.7 on 2020-06-16 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0010_auto_20200616_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('package_name', models.CharField(default='', max_length=100)),
                ('package_url', models.CharField(default='', max_length=100)),
                ('package_price', models.IntegerField()),
                ('package_discount', models.IntegerField()),
                ('package_overview', models.CharField(default='', max_length=100000)),
                ('package_itinerary', models.CharField(default='', max_length=100000)),
                ('meta_tags', models.CharField(default='', max_length=1024)),
                ('meta_keywords', models.CharField(default='', max_length=2048)),
                ('meta_description', models.CharField(default='', max_length=100000)),
                ('package_image', models.ImageField(default='', upload_to='BackendImages/Packages')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelsapp.Category')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelsapp.Section')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
