# Generated by Django 3.0.7 on 2020-06-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0013_auto_20200621_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='best_value',
            field=models.BooleanField(default=False),
        ),
    ]
