# Generated by Django 3.0.7 on 2020-06-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0014_packages_best_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_image',
            field=models.ImageField(default='', height_field=300, upload_to='BackendImages/Packages', width_field=300),
        ),
    ]
