# Generated by Django 3.0.7 on 2020-06-21 07:30

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0017_auto_20200621_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='packages',
            name='package_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[500, 400], upload_to='BackendImages/Packages'),
        ),
    ]
