# Generated by Django 3.0.7 on 2020-06-21 10:26

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0018_auto_20200621_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=100, size=[1920, 1080], upload_to='BackendImages/Packages'),
        ),
    ]
