# Generated by Django 3.0.7 on 2020-06-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0019_auto_20200621_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_overview',
            field=models.TextField(default=''),
        ),
    ]
