# Generated by Django 3.0.7 on 2020-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0020_auto_20200621_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packages',
            name='package_itinerary',
            field=models.TextField(default=''),
        ),
    ]
