# Generated by Django 3.0.7 on 2020-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0021_auto_20200621_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('package_name', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=50)),
                ('count', models.CharField(default='', max_length=100)),
                ('date', models.DateTimeField()),
                ('pickup', models.CharField(default='', max_length=2000)),
                ('message', models.CharField(default='', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
