# Generated by Django 3.0.7 on 2020-06-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsapp', '0023_auto_20200621_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_desc',
            field=models.TextField(default=''),
        ),
    ]
